### ISSUE TITLE
GCSA compression

### ISSUE THREAD

**Issue by jltsiren** [jltsiren/gcsa2#13]
Many components of GCSA can be compressed to reduce the size of the index in memory. There is always a trade-off: compressing the components will make the queries slower. The following numbers are for a whole-genome graph (`-e 4`, path length 64, 5.27 billion paths).

The GCSA takes 9444 MB, but it can be compressed to 6174 MB. This can be broken down as follows:
- **BWT:** 2142 MB -> 1140 MB, high impact on performance
- **Node/edge mapping:** 1907 MB -> 367 MB, high impact
- **Sampled BWT positions:** 785 MB -> 328 MB, moderate impact
- **Sampled nodes:** 4610 MB -> 4342 MB, low impact

(There are also SDSL visualizations of the size breakdowns of the [original](http://jltsiren.kapsi.fi/stuff/human_e4_d2.html) and [compressed](http://jltsiren.kapsi.fi/stuff/human_e4_d2_alt.html) GCSA.)

There are 918 million samples representing 593 million distinct nodes. Because the samples will take at least 3 GB, no matter how we compress them, compressing the index doesn't sound too beneficial.

**Comment by ekg** [comment]
Right now my sense is that query performance would be the limiting factor.
Do you have an idea of how much worse the query performance would be to
obtain a 30% reduction in memory usage?

**Comment by jltsiren** [comment]
A fully compressed GCSA would probably be 3-5 times slower.

**Comment by jltsiren** [comment]
This was settled with the new encoding, which made the index several times faster and a bit smaller.
