### ISSUE TITLE
debugging output via option rather than macro

### ISSUE THREAD

**Issue by ekg** [jltsiren/gcsa2#19]
Right now GCSA2 uses `#ifdef VERBOSE_STATUS_INFO` macros to enable or disable debugging information during builds.

In `vg` we sometimes want to see the debugging information (say, when building a whole genome index) and other times it is superfluous (such as when we're building 10 GCSAs a second in `vg msga`).

I guess I'd like to also make output dependent on a runtime-configurable debug flag. Any ideas about the best way to do it?

**Comment by jltsiren** [comment]
I can think of two options. Either choose the verbosity level via a global variable, or we add it to `InputGraph` and/or `ConstructionParameters`. Both options require some refactoring, but I can probably find the time for it this week.

**Comment by ekg** [comment]
Probably adding it to the constructionparameters would be the simplest
thing. It's not a major issue but will make it easier to see what's going
on when calling gcsa2 from vg.

**Comment by jltsiren** [comment]
A global verbosity setting seems to be the simpler option. Otherwise we would have to set verbosity in several places.

**Comment by ekg** [comment]
Fair enough. I forgot that this will not be a problem due to namespacing.

**Comment by jltsiren** [comment]
Verbosity level can now be set using `Verbosity::set()`. See [the wiki](https://github.com/jltsiren/gcsa2/wiki/Construction-Interface) for some documentation.
