### ISSUE TITLE
k<16 input graph

### ISSUE THREAD

**Issue by ekg** [jltsiren/gcsa2#27]
In discussion you mentioned there are problems in using kmers shorter than 16. I am interested in using them for various reasons, so I'd like to understand the limitations.

**Comment by jltsiren** [comment]
I forgot to consider this before my holiday.

I'm not actually sure what happens with short kmers. My implicit assumption has been that the number of distinct kmers should be within the same order of magnitude as the total number of paths in the `.graph` files. (In other words, k should be close to the base-4 logarithm of the amount of sequence in the variation graph.) I can't see any obvious problems with shorter kmers, but I haven't tried to use them either.
