### ISSUE TITLE
Rare issues in edge generation

### ISSUE THREAD

**Issue by jltsiren** [jltsiren/gcsa2#3]
Assume that we have the following subgraphs:

```
1: B[CD]F[GH]J
2: [AB]C[EF]GI
```

There are the following paths of length 4:

```
(1,1): BCFG, BCFH, BDFG, BDFH
(1,2): CFGJ, CFHJ, DFGJ, DFHJ
(2,1): ACEG, ACFG, BCEG, BCFG
(2,2): CEGI, CFGI
```

If we start from paths of length 2 and do one step of prefix-doubling, we end up with the following list of paths:

```
(2,1): ACEG to BCEG
(1,1): BCFG
(2,1): BCFG
(1,1): BCFH to BDFH
(2,2): CEGI to CFGI
(1,2): CFGJ to DFHJ
```

The path graph has six nodes and four edges:

```
[(2,1): ACEG to BCEG] -> [(2,2): CEGI to CFGI] on A, B
[(2,1): BCFG]         -> [(2,2): CEGI to CFGI] on B
[(1,1): BCFG]         -> [(1,2): CFGJ to DFHJ] on B
[(1,1): BCFH to BDFH] -> [(1,2): CFGJ to DFHJ] on B
```

If we perform the final merge-by-label step, we end up with five nodes and four edges:

```
[(2,1): ACEG to BCEG] -> [(2,2): CEGI to CFGI] on A, B
[(1,1), (2,1): BCFG]  -> [(2,2): CEGI to CFGI] on B
[(1,1), (2,1): BCFG]  -> [(1,2): CFGJ to DFHJ] on B
[(1,1): BCFH to BDFH] -> [(1,2): CFGJ to DFHJ] on B
```

By doing backward searching in this graph, we could end up at (1,1) with pattern BCE and at (2,1) with pattern BD, which are both wrong.

The real issue is that the the merging step in prefix-doubling and the final merge-by-label step are incompatible. In some very rare cases (such as the example above), they will result in an incorrect path graph. The merge-by-label step is less useful, so we are probably going to drop it.

The remaining issue is how we can match the destination node of an edge with the correct source node, out of a set of path nodes with identical labels.

**Comment by ekg** [comment]
Would it help to have the original graph available? I have an
implementation which will provide this in <10GB for a graph of the
1000G+GRCh37. The edges alone require much less space.

**Comment by ekg** [comment]
I am referring to https://github.com/ekg/succinct-graph.

**Comment by jltsiren** [comment]
I think there may be an easier solution than I thought yesterday. Right now the merging step works like in the original GCSA, merging lexicographic ranges of paths, if they all start from the same node. The issue should go away, if the merging is based on a common prefix instead of any lexicographic range. (In the terminology of the GCSA paper, this means switching from prefix-range-sorted automata to prefix-sorted automata.)

**Comment by ekg** [comment]
Where is the merge implemented?

**Comment by ekg** [comment]
https://github.com/jltsiren/gcsa2/blob/master/gcsa.cpp :)

Silly question.

**Comment by jltsiren** [comment]
The idea worked. Memory usage and index size are temporarily up, as I'm merging paths according to prefixes of length divisible by k at the moment. Merging according to arbitrary prefixes requires further work.
