### ISSUE TITLE
utils.h keys on compiler and not C++ standard library to decide whether to try and use parallel sort

### ISSUE THREAD

**Issue by adamnovak** [jltsiren/gcsa2#38]
I'm building GCSA2 with GNU GCC and Apple libc++ (instead of GNU libstdc++), in order to try and get vg builds working with GNU GCC and Homebrew's binary Protobuf library on Mac (which links against libc++).

GCSA2 checks the compiler identity, and uses that to decide whether the standard library has GNU's `parallel/algorithm` nonstandard header. This doesn't work if you are using GNU GCC with anything other than libstdc++, and it misses out on using the header if you are using libstdc++ with any other compiler.

https://github.com/jltsiren/gcsa2/blob/145c4ee5c3e06289620e1d93ee3586bffd7590da/include/gcsa/utils.h#L41-L44

It looks like [the Right Way to detect libc++](https://stackoverflow.com/a/31658120/402891) is to include any standard library header and then check if `_LIBCPP_VERSION` is defined. For detecting libstdc++, you can incluse *nearly* any standard header and check for `__GLIBCXX__`.

We should only use `parallel/algorithm` if `__GLIBCXX__` is defined, instead of keying on the compiler.

**Comment by jltsiren** [comment]
I just fixed this here and in GBWT.
