### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by xuyuannnn** [jltsiren/gcsa2#41]
Hi, when I compile this codes ,it fails , the screen print like this , what can I for this issue? thanks for your help!

Installing GCSA2 to '/data/home/xuyuan/biosoft/gcsa2'.
Running 20 parallel make jobs.
/opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -std=c++11 -Wall -Wextra -DNDEBUG   -fopenmp -pthread -O3 -ffast-math -funroll-loops -msse4.2 -march=native -msse4.2 -march=native -DHAVE_CXA_DEMANGLE -Iinclude -I/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include -c algorithms.cpp
/opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -std=c++11 -Wall -Wextra -DNDEBUG   -fopenmp -pthread -O3 -ffast-math -funroll-loops -msse4.2 -march=native -msse4.2 -march=native -DHAVE_CXA_DEMANGLE -Iinclude -I/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include -c dbg.cpp
/opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -std=c++11 -Wall -Wextra -DNDEBUG   -fopenmp -pthread -O3 -ffast-math -funroll-loops -msse4.2 -march=native -msse4.2 -march=native -DHAVE_CXA_DEMANGLE -Iinclude -I/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include -c files.cpp
/opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -std=c++11 -Wall -Wextra -DNDEBUG   -fopenmp -pthread -O3 -ffast-math -funroll-loops -msse4.2 -march=native -msse4.2 -march=native -DHAVE_CXA_DEMANGLE -Iinclude -I/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include -c gcsa.cpp
/opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -std=c++11 -Wall -Wextra -DNDEBUG   -fopenmp -pthread -O3 -ffast-math -funroll-loops -msse4.2 -march=native -msse4.2 -march=native -DHAVE_CXA_DEMANGLE -Iinclude -I/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include -c internal.cpp
/opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -std=c++11 -Wall -Wextra -DNDEBUG   -fopenmp -pthread -O3 -ffast-math -funroll-loops -msse4.2 -march=native -msse4.2 -march=native -DHAVE_CXA_DEMANGLE -Iinclude -I/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include -c lcp.cpp
/opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -std=c++11 -Wall -Wextra -DNDEBUG   -fopenmp -pthread -O3 -ffast-math -funroll-loops -msse4.2 -march=native -msse4.2 -march=native -DHAVE_CXA_DEMANGLE -Iinclude -I/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include -c path_graph.cpp
/opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -std=c++11 -Wall -Wextra -DNDEBUG   -fopenmp -pthread -O3 -ffast-math -funroll-loops -msse4.2 -march=native -msse4.2 -march=native -DHAVE_CXA_DEMANGLE -Iinclude -I/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include -c support.cpp
/opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -std=c++11 -Wall -Wextra -DNDEBUG   -fopenmp -pthread -O3 -ffast-math -funroll-loops -msse4.2 -march=native -msse4.2 -march=native -DHAVE_CXA_DEMANGLE -Iinclude -I/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include -c utils.cpp
/opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -std=c++11 -Wall -Wextra -DNDEBUG   -fopenmp -pthread -O3 -ffast-math -funroll-loops -msse4.2 -march=native -msse4.2 -march=native -DHAVE_CXA_DEMANGLE -Iinclude -I/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include -c build_gcsa.cpp
/opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -std=c++11 -Wall -Wextra -DNDEBUG   -fopenmp -pthread -O3 -ffast-math -funroll-loops -msse4.2 -march=native -msse4.2 -march=native -DHAVE_CXA_DEMANGLE -Iinclude -I/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include -c convert_graph.cpp
/opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -std=c++11 -Wall -Wextra -DNDEBUG   -fopenmp -pthread -O3 -ffast-math -funroll-loops -msse4.2 -march=native -msse4.2 -march=native -DHAVE_CXA_DEMANGLE -Iinclude -I/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include -c gcsa_format.cpp
/opt/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -std=c++11 -Wall -Wextra -DNDEBUG   -fopenmp -pthread -O3 -ffast-math -funroll-loops -msse4.2 -march=native -msse4.2 -march=native -DHAVE_CXA_DEMANGLE -Iinclude -I/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include -c try_extend.cpp
In file included from include/gcsa/dbg.h:28:0,
                 from dbg.cpp:26:
include/gcsa/support.h: In constructor 'gcsa::SadaSparse::SadaSparse(const Container&)':
include/gcsa/support.h:351:52: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     if(source[i] > 0) { tail += source[i]; builder.set_unsafe(tail - 1); }
                                                    ^~~~~~~~~~
In file included from internal.cpp:26:0:
include/gcsa/internal.h: In constructor 'gcsa::ValueIndex<ValueType, Getter>::ValueIndex(const std::vector<_RealType>&)':
include/gcsa/internal.h:127:51: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     for(const ValueType& value : input) { builder.set_unsafe(Getter::get(value)); }
                                                   ^~~~~~~~~~
include/gcsa/internal.h: In member function 'gcsa::size_type gcsa::ValueIndex<ValueType, Getter>::find(gcsa::size_type) const':
include/gcsa/internal.h:136:30: error: 'const class sdsl::sd_vector<>' has no member named 'successor'
     auto iter = this->values.successor(value);
                              ^~~~~~~~~
include/gcsa/internal.h:137:64: error: 'const class sdsl::sd_vector<>' has no member named 'ones'
     return (iter->second == value ? iter->first : this->values.ones());
                                                                ^~~~
In file included from support.cpp:26:0:
include/gcsa/support.h: In constructor 'gcsa::SadaSparse::SadaSparse(const Container&)':
include/gcsa/support.h:351:52: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     if(source[i] > 0) { tail += source[i]; builder.set_unsafe(tail - 1); }
                                                    ^~~~~~~~~~
In file included from support.cpp:27:0:
include/gcsa/internal.h: In constructor 'gcsa::ValueIndex<ValueType, Getter>::ValueIndex(const std::vector<_RealType>&)':
include/gcsa/internal.h:127:51: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     for(const ValueType& value : input) { builder.set_unsafe(Getter::get(value)); }
                                                   ^~~~~~~~~~
include/gcsa/internal.h: In member function 'gcsa::size_type gcsa::ValueIndex<ValueType, Getter>::find(gcsa::size_type) const':
include/gcsa/internal.h:136:30: error: 'const class sdsl::sd_vector<>' has no member named 'successor'
     auto iter = this->values.successor(value);
                              ^~~~~~~~~
include/gcsa/internal.h:137:64: error: 'const class sdsl::sd_vector<>' has no member named 'ones'
     return (iter->second == value ? iter->first : this->values.ones());
                                                                ^~~~
make: *** [Makefile:47: internal.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from utils.cpp:36:0:
include/gcsa/internal.h: In constructor 'gcsa::ValueIndex<ValueType, Getter>::ValueIndex(const std::vector<_RealType>&)':
include/gcsa/internal.h:127:51: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     for(const ValueType& value : input) { builder.set_unsafe(Getter::get(value)); }
                                                   ^~~~~~~~~~
include/gcsa/internal.h: In member function 'gcsa::size_type gcsa::ValueIndex<ValueType, Getter>::find(gcsa::size_type) const':
include/gcsa/internal.h:136:30: error: 'const class sdsl::sd_vector<>' has no member named 'successor'
     auto iter = this->values.successor(value);
                              ^~~~~~~~~
include/gcsa/internal.h:137:64: error: 'const class sdsl::sd_vector<>' has no member named 'ones'
     return (iter->second == value ? iter->first : this->values.ones());
                                                                ^~~~
make: *** [Makefile:47: dbg.o] Error 1
In file included from include/gcsa/dbg.h:28:0,
                 from include/gcsa/path_graph.h:29,
                 from path_graph.cpp:26:
include/gcsa/support.h: In constructor 'gcsa::SadaSparse::SadaSparse(const Container&)':
include/gcsa/support.h:351:52: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     if(source[i] > 0) { tail += source[i]; builder.set_unsafe(tail - 1); }
                                                    ^~~~~~~~~~
In file included from include/gcsa/files.h:29:0,
                 from convert_graph.cpp:25:
include/gcsa/support.h: In constructor 'gcsa::SadaSparse::SadaSparse(const Container&)':
include/gcsa/support.h:351:52: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     if(source[i] > 0) { tail += source[i]; builder.set_unsafe(tail - 1); }
                                                    ^~~~~~~~~~
In file included from include/gcsa/path_graph.h:31:0,
                 from path_graph.cpp:26:
include/gcsa/internal.h: In constructor 'gcsa::ValueIndex<ValueType, Getter>::ValueIndex(const std::vector<_RealType>&)':
include/gcsa/internal.h:127:51: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     for(const ValueType& value : input) { builder.set_unsafe(Getter::get(value)); }
                                                   ^~~~~~~~~~
include/gcsa/internal.h: In member function 'gcsa::size_type gcsa::ValueIndex<ValueType, Getter>::find(gcsa::size_type) const':
include/gcsa/internal.h:136:30: error: 'const class sdsl::sd_vector<>' has no member named 'successor'
     auto iter = this->values.successor(value);
                              ^~~~~~~~~
include/gcsa/internal.h:137:64: error: 'const class sdsl::sd_vector<>' has no member named 'ones'
     return (iter->second == value ? iter->first : this->values.ones());
                                                                ^~~~
In file included from include/gcsa/files.h:29:0,
                 from files.cpp:26:
include/gcsa/support.h: In constructor 'gcsa::SadaSparse::SadaSparse(const Container&)':
include/gcsa/support.h:351:52: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     if(source[i] > 0) { tail += source[i]; builder.set_unsafe(tail - 1); }
                                                    ^~~~~~~~~~
In file included from include/gcsa/files.h:29:0,
                 from include/gcsa/gcsa.h:29,
                 from gcsa_format.cpp:28:
include/gcsa/support.h: In constructor 'gcsa::SadaSparse::SadaSparse(const Container&)':
include/gcsa/support.h:351:52: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     if(source[i] > 0) { tail += source[i]; builder.set_unsafe(tail - 1); }
                                                    ^~~~~~~~~~
In file included from files.cpp:27:0:
include/gcsa/internal.h: In constructor 'gcsa::ValueIndex<ValueType, Getter>::ValueIndex(const std::vector<_RealType>&)':
include/gcsa/internal.h:127:51: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     for(const ValueType& value : input) { builder.set_unsafe(Getter::get(value)); }
                                                   ^~~~~~~~~~
include/gcsa/internal.h: In member function 'gcsa::size_type gcsa::ValueIndex<ValueType, Getter>::find(gcsa::size_type) const':
include/gcsa/internal.h:136:30: error: 'const class sdsl::sd_vector<>' has no member named 'successor'
     auto iter = this->values.successor(value);
                              ^~~~~~~~~
include/gcsa/internal.h:137:64: error: 'const class sdsl::sd_vector<>' has no member named 'ones'
     return (iter->second == value ? iter->first : this->values.ones());
                                                                ^~~~
In file included from include/gcsa/files.h:29:0,
                 from include/gcsa/gcsa.h:29,
                 from include/gcsa/algorithms.h:29,
                 from gcsa.cpp:26:
include/gcsa/support.h: In constructor 'gcsa::SadaSparse::SadaSparse(const Container&)':
include/gcsa/support.h:351:52: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     if(source[i] > 0) { tail += source[i]; builder.set_unsafe(tail - 1); }
                                                    ^~~~~~~~~~
In file included from include/gcsa/files.h:29:0,
                 from include/gcsa/gcsa.h:29,
                 from include/gcsa/algorithms.h:29,
                 from algorithms.cpp:26:
include/gcsa/support.h: In constructor 'gcsa::SadaSparse::SadaSparse(const Container&)':
include/gcsa/support.h:351:52: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     if(source[i] > 0) { tail += source[i]; builder.set_unsafe(tail - 1); }
                                                    ^~~~~~~~~~
In file included from include/gcsa/files.h:29:0,
                 from include/gcsa/lcp.h:29,
                 from lcp.cpp:26:
include/gcsa/support.h: In constructor 'gcsa::SadaSparse::SadaSparse(const Container&)':
include/gcsa/support.h:351:52: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     if(source[i] > 0) { tail += source[i]; builder.set_unsafe(tail - 1); }
                                                    ^~~~~~~~~~
In file included from gcsa.cpp:27:0:
include/gcsa/internal.h: In constructor 'gcsa::ValueIndex<ValueType, Getter>::ValueIndex(const std::vector<_RealType>&)':
include/gcsa/internal.h:127:51: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     for(const ValueType& value : input) { builder.set_unsafe(Getter::get(value)); }
                                                   ^~~~~~~~~~
include/gcsa/internal.h: In member function 'gcsa::size_type gcsa::ValueIndex<ValueType, Getter>::find(gcsa::size_type) const':
include/gcsa/internal.h:136:30: error: 'const class sdsl::sd_vector<>' has no member named 'successor'
     auto iter = this->values.successor(value);
                              ^~~~~~~~~
include/gcsa/internal.h:137:64: error: 'const class sdsl::sd_vector<>' has no member named 'ones'
     return (iter->second == value ? iter->first : this->values.ones());
                                                                ^~~~
In file included from lcp.cpp:30:0:
include/gcsa/internal.h: In constructor 'gcsa::ValueIndex<ValueType, Getter>::ValueIndex(const std::vector<_RealType>&)':
include/gcsa/internal.h:127:51: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     for(const ValueType& value : input) { builder.set_unsafe(Getter::get(value)); }
                                                   ^~~~~~~~~~
include/gcsa/internal.h: In member function 'gcsa::size_type gcsa::ValueIndex<ValueType, Getter>::find(gcsa::size_type) const':
include/gcsa/internal.h:136:30: error: 'const class sdsl::sd_vector<>' has no member named 'successor'
     auto iter = this->values.successor(value);
                              ^~~~~~~~~
include/gcsa/internal.h:137:64: error: 'const class sdsl::sd_vector<>' has no member named 'ones'
     return (iter->second == value ? iter->first : this->values.ones());
                                                                ^~~~
In file included from algorithms.cpp:30:0:
include/gcsa/internal.h: In constructor 'gcsa::ValueIndex<ValueType, Getter>::ValueIndex(const std::vector<_RealType>&)':
include/gcsa/internal.h:127:51: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     for(const ValueType& value : input) { builder.set_unsafe(Getter::get(value)); }
                                                   ^~~~~~~~~~
include/gcsa/internal.h: In member function 'gcsa::size_type gcsa::ValueIndex<ValueType, Getter>::find(gcsa::size_type) const':
include/gcsa/internal.h:136:30: error: 'const class sdsl::sd_vector<>' has no member named 'successor'
     auto iter = this->values.successor(value);
                              ^~~~~~~~~
include/gcsa/internal.h:137:64: error: 'const class sdsl::sd_vector<>' has no member named 'ones'
     return (iter->second == value ? iter->first : this->values.ones());
                                                                ^~~~
make: *** [Makefile:47: support.o] Error 1
include/gcsa/internal.h: In instantiation of 'gcsa::ValueIndex<ValueType, Getter>::ValueIndex(const std::vector<_RealType>&) [with ValueType = gcsa::PathNode; Getter = gcsa::FromGetter]':
path_graph.cpp:959:54:   required from here
include/gcsa/internal.h:126:29: error: no matching function for call to 'sdsl::sd_vector_builder::sd_vector_builder(gcsa::size_type, std::vector<gcsa::PathNode>::size_type, bool)'
     sdsl::sd_vector_builder builder(Getter::get(input.back()) + 1, input.size(), true);
                             ^~~~~~~
In file included from /data/home/xuyuan/biosoft/sdsl/sdsl-lite/include/sdsl/bit_vectors.hpp:11:0,
                 from /data/home/xuyuan/biosoft/sdsl/sdsl-lite/include/sdsl/wt_pc.hpp:25,
                 from /data/home/xuyuan/biosoft/sdsl/sdsl-lite/include/sdsl/wavelet_trees.hpp:32,
                 from include/gcsa/utils.h:36,
                 from include/gcsa/support.h:29,
                 from include/gcsa/dbg.h:28,
                 from include/gcsa/path_graph.h:29,
                 from path_graph.cpp:26:
/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include/sdsl/sd_vector.hpp:80:9: note: candidate: sdsl::sd_vector_builder::sd_vector_builder(sdsl::sd_vector_builder::size_type, sdsl::sd_vector_builder::size_type)
         sd_vector_builder(size_type n, size_type m);
         ^~~~~~~~~~~~~~~~~
/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include/sdsl/sd_vector.hpp:80:9: note:   candidate expects 2 arguments, 3 provided
/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include/sdsl/sd_vector.hpp:74:9: note: candidate: sdsl::sd_vector_builder::sd_vector_builder()
         sd_vector_builder();
         ^~~~~~~~~~~~~~~~~
/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include/sdsl/sd_vector.hpp:74:9: note:   candidate expects 0 arguments, 3 provided
/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include/sdsl/sd_vector.hpp:56:7: note: candidate: sdsl::sd_vector_builder::sd_vector_builder(const sdsl::sd_vector_builder&)
 class sd_vector_builder
       ^~~~~~~~~~~~~~~~~
/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include/sdsl/sd_vector.hpp:56:7: note:   candidate expects 1 argument, 3 provided
/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include/sdsl/sd_vector.hpp:56:7: note: candidate: sdsl::sd_vector_builder::sd_vector_builder(sdsl::sd_vector_builder&&)
/data/home/xuyuan/biosoft/sdsl/sdsl-lite/include/sdsl/sd_vector.hpp:56:7: note:   candidate expects 1 argument, 3 provided
make: *** [Makefile:47: utils.o] Error 1
In file included from include/gcsa/dbg.h:28:0,
                 from include/gcsa/path_graph.h:29,
                 from try_extend.cpp:25:
include/gcsa/support.h: In constructor 'gcsa::SadaSparse::SadaSparse(const Container&)':
include/gcsa/support.h:351:52: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     if(source[i] > 0) { tail += source[i]; builder.set_unsafe(tail - 1); }
                                                    ^~~~~~~~~~
In file included from include/gcsa/files.h:29:0,
                 from include/gcsa/gcsa.h:29,
                 from include/gcsa/algorithms.h:29,
                 from build_gcsa.cpp:29:
include/gcsa/support.h: In constructor 'gcsa::SadaSparse::SadaSparse(const Container&)':
include/gcsa/support.h:351:52: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     if(source[i] > 0) { tail += source[i]; builder.set_unsafe(tail - 1); }
                                                    ^~~~~~~~~~
In file included from include/gcsa/path_graph.h:31:0,
                 from try_extend.cpp:25:
include/gcsa/internal.h: In constructor 'gcsa::ValueIndex<ValueType, Getter>::ValueIndex(const std::vector<_RealType>&)':
include/gcsa/internal.h:127:51: error: 'class sdsl::sd_vector_builder' has no member named 'set_unsafe'
     for(const ValueType& value : input) { builder.set_unsafe(Getter::get(value)); }
                                                   ^~~~~~~~~~
include/gcsa/internal.h: In member function 'gcsa::size_type gcsa::ValueIndex<ValueType, Getter>::find(gcsa::size_type) const':
include/gcsa/internal.h:136:30: error: 'const class sdsl::sd_vector<>' has no member named 'successor'
     auto iter = this->values.successor(value);
                              ^~~~~~~~~
include/gcsa/internal.h:137:64: error: 'const class sdsl::sd_vector<>' has no member named 'ones'
     return (iter->second == value ? iter->first : this->values.ones());
                                                                ^~~~
make: *** [Makefile:47: convert_graph.o] Error 1
make: *** [Makefile:47: gcsa_format.o] Error 1
make: *** [Makefile:47: lcp.o] Error 1
make: *** [Makefile:47: build_gcsa.o] Error 1
make: *** [Makefile:47: files.o] Error 1
make: *** [Makefile:47: try_extend.o] Error 1
make: *** [Makefile:47: algorithms.o] Error 1
make: *** [Makefile:47: path_graph.o] Error 1
make: *** [Makefile:47: gcsa.o] Error 1
Error: Could not compile GCSA2

**Comment by jltsiren** [comment]
GCSA2 now requires the [vgteam fork of SDSL](https://github.com/vgteam/sdsl-lite), because the official SDSL 2 has been abandoned by its developers.
