### ISSUE TITLE
Backward search returns non-empty interval even if pattern is not in the graph

### ISSUE THREAD

**Issue by ldenti** [jltsiren/gcsa2#44]
Hi Jouni,
I was playing with the gcsa2 index and I encountered a strange behaviour: if I manually backward search a pattern in the index or by using the `find()`, it returns a non-empty interval of size 1 altough I'm pretty sure that it's not in the graph.. The pattern is quite long (>1600bp).

I can prepare the test data and send you my code to test it, but before doing that I'd like to do some more tests and also know if there is a limit on the pattern size. If that's the case, then there is nothing we can do.

I built the gcsa2 index using `vg index` (version: v1.46.0 "Altamura").

Thanks,
Luca

**Comment by jltsiren** [comment]
This is intentional behavior. GCSA2 uses a de Bruijn graph to approximate the original graph. Patterns longer than the order of the DBG (256 by default) can be false positives.

**Comment by ldenti** [comment]
Oh, I see. Now I recall I read it somewhere and I just realized it was in the README.. Thanks!
