### ISSUE TITLE
Binary input format

### ISSUE THREAD

**Issue by jltsiren** [jltsiren/gcsa2#6]
The text format we've used so far has been useful for debugging various issues during GCSA development. Now as we're moving toward larger graphs, generating, transferring, and parsing the text has become a significant bottleneck. I think it's time to start using a binary format instead.

I've never developed file formats for production use, so I'm open to suggestions. In particular, I'm interested in best practices for not breaking backward compatibility when the requirements for the file format change.

This is what I've been thinking so far:
### General
- Keep the file format simple. Every field should be an unsigned 64-bit integer.
- Make it efficient for GCSA. The bulk of the file should be directly readable into a `std::vector<KMer>`.
- Make it efficient for vg. What does this imply?
- The text format apparently has an useful property. If we generate the files for different chromosomes separately with the same kmer length, and then concatenate the files, the result is a valid input for indexing the entire genome. This should be true with the binary format as well.
- The file consists of one or more sections. Each section starts with a header, followed by data.
### Header
- One field for future use. Right now, we should set it to 0.
- The number of paths in the section.
- The length of path labels.
### Data
- `KMer` structures in arbitrary order.
- Each structure consists of three fields: `key`, `from`, and `to`.
### `key`
- Created by `Key::encode(const Alphabet& alpha, const std::string& kmer, byte_type pred, byte_type succ)`.
- `alpha` is an object that maps between characters and the comp values (the internal alphabet of GCSA). The default constructor of `Alphabet` creates an object that maps `$ACGTN#` to 0-6.
- `kmer` is the fixed-length label of the path.
- `pred` encodes the set of characters that occur immediately before the path. `pred & (1 << comp)` is true iff `comp` is a comp value for a character in the set.
- `succ` encodes the set of characters occurring immediately after the path in the same way.
### `from`
- Encodes the starting position of the path.
- Created by `Node::encode(size_type node_id, size_type node_offset)`.
- `node_id` is the identifier of the vg node where the path starts. We have 54 bits available for encoding the identifier, but using excessively large identifiers is probably a bad idea. The identifiers of different nodes do not have to form a contiguous range.
- `node_offset` is the starting offset (in the label of the node) for the path. We have 10 bits available, so acceptable offsets range from 0 to 1023. The offsets in the same node should obviously be contiguous.
### `to`
- Encodes a position **immediately after** the end of the path in the same way as `from`.
- If the path has multiple successors, a separate `KMer` object with different `to` fields is created for each of them.
- If multiple `KMer` objects are created for the same path, the `succ` field of the `key` can encode either all successor characters or just the one at position `to`, whichever is more convenient.

**Comment by jltsiren** [comment]
This binary format is now the default graph format. The old text format can still be used with `build_gcsa -t`. Graphs can be converted from text format to binary format using `convert_graph`.

The above description should be accurate, apart from the encoding of positions. The bit between the 53-bit identifier and the 10-bit offset now encodes node orientation. This is equivalent to encoding the forward orientation of node _x_ as _2x_ and the reverse complement orientation as _2x+1_.

**Comment by ekg** [comment]
Can we stream through convert_graph?

**Comment by jltsiren** [comment]
Now it's kind of possible. `convert_graph` without any parameters reads from stdin and writes to stdout, while `convert_graph a b` converts `a.gcsa2` into `a.graph` and `b.gcsa2` into `b.graph`.

At the moment, `convert_graph` reads all kmers from the current input before writing them. I'll implement proper streaming later.

**Comment by jltsiren** [comment]
The input formats are now documented in the wiki.
