### ISSUE TITLE
thread safety

### ISSUE THREAD

**Issue by ekg** [jltsiren/gcsa2#9]
Via xg/vg integration, I've noticed that some features of sdsl-lite are not thread safe (at least this is referred to [in sdsl-lite issues](https://github.com/simongog/sdsl-lite/issues/235)). Is GCSA2 thread safe? In scaling up mapping we need to run with multiple threads.

**Comment by jltsiren** [comment]
It should be thread safe, but I may have missed something. `GCSA::verifyIndex()` queries the index with multiple threads, so if some problems remain, they should be rare.

**Comment by ekg** [comment]
I did run into some thread safety issues. I just put a PR in to resolve them in sdsl-lite https://github.com/simongog/sdsl-lite/pull/264.

**Comment by ekg** [comment]
Sorry, these are for xg, not gcsa2.
